# Generated by Django 5.0 on 2023-12-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('negociate', 'Negociate')], max_length=20)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='userrequests.userrequest')),
            ],
        ),
    ]
